### PR TITLE
Documentation pool.js

### PR DESCRIPTION
**Pull request by arejula27**
I spend a time studying the pool.js , at the same time i make some anotations.Maybe coud be a good option to add it.

### CODE REVIEW

**Comment by arejula27** [comment]
I noticed that when you publish a event never rejects, so it will be blocked. It is a correct behaviour?

**Comment by fiatjaf** [comment]
In theory yes, but we could put a timeout there.

And we must also add support for https://github.com/nostr-protocol/nips/blob/master/20.md, so we can get an `OK` (or not ok) response for each event published.

**Comment by arejula27** [comment]
i could try it, where can i see the status codes?

**Comment by fiatjaf** [comment]
What status codes? It's either `["OK", <id>, true]` or `["OK", <id>, false]` and then a string message. Some relays will return that right after you send an event.

**Comment by arejula27** [comment]
image

That status, o dodnt dont understand what does it mean. 

As i see the implementation of the nip 2o will be on the line 116 of the relay.js, so i dont understant what the previous status means. Also could be interesting do a publish sincronous and asyncrous. Im currently studing diffents approaches

**Comment by arejula27** [comment]
Can this pr be merged?

**Pull request merged**
